const PageContent=[
   {
     id:1,
     about: "About KASHMIR VALLEY",
     text:"Famous for its enthralling Dal Lake, Srinagar is an enchanting city of Kashmir blessed with several attractions. The city is known as the summer capital of Jammu & Kashmir, where tourists come from all over the world. A shikara ride on pristine Dal Lake, luxurious houseboats, snow-capped mountains, beautiful handicrafts and lovely gardens are the popular attractions of Srinagar.Pahalgam is another amazing destination we will cover under the Kashmir tour itinerary for 3N 4D. This valley is famed as the ‘Valley of Shepherds’. It is a great destination to experience the unparalleled charm of mother nature beautifully reflected in snow-capped mountains, gorgeous landscapes, pleasant weather, fresh air and adventure activities such as pony rides, trekking and river rafting. The next destination on your Kashmir Tour for 3N 4D is the enchanting Gulmarg Valley, known as ‘the Meadow of Flowers’. This valley is a world-famous skiing destination, a great place for trekking and a heavenly destination for honeymooners. You must try out its breathtaking Gondola Ride, offering the sheer natural beauty of snow-covered mountains and an abundance of adventure.",
     itinerary: "Itinerary",
     Day1:"DAY 1 : Arrive at Srinagar (Height 1,585 m)",
     p1:"Arrive at the Srinagar airport/railway station! Our representative will welcome you warmly and drive you to the houseboat in Srinagar. Check in at the houseboat and get the feel of it. After that, you can go out for a leisurely walk on Boulevard Road which offers majestic views of Zabarwan Mountain Ranges. Now it’s time to enjoy a Shikara Ride on Dal Lake (1-hour ride). After the ride, you can go shopping in Srinagar to take back home some amazing souvenirs such as pashmina shawls, embroidered sari, saffron, walnut wood items, etc. Post that, come back to the houseboat for a memorable stay. Stay overnight.",
     Day2:"DAY 2 : Srinagar to Pahalgam (88.8 km; 2hrs and 18 mins; Pahalgam height: 2,740 m)",
     p2:"Post breakfast, we will drive you to the mesmerizing Pahalgam Valley. En route from Srinagar to Pahalgam, you will come across saffron fields which bloom with (in season) vibrant purple flowers! It is a sight to behold. The first attraction of Pahalgam Valley that we will visit is the famous Betaab Valley soaked in natural beauty. This valley derived its name from the popular Bollywood movie ‘Betaab’ which was shot here. The delightful Lidder River passes through this valley offering picture-perfect views.Then we head to the next attraction of Pahalgam i.e. Chandanwari Valley (7 km) located at an altitude of 2,895 m. This valley is the starting point for the famous Hindu pilgrimage ‘Amarnath Yatra’. Visit this valley in winter to enjoy sledding and capturing the enchanting sights of glaciers. Next on the list is the captivating Aru Valley which is located at an altitude of 2,414 m. It boasts snow-covered mountain peaks, lush green meadows, beautiful lakes, and much more. It serves as a great destination for skiing and heli-skiing in winter. The trekking tours to Tarsar Lake and Kolahoi Glacier start from this valley.By late evening, we will drive you to the hotel in Pahalgam for an overnight stay.",
     Day3:"DAY 3 : Travel from Pahalgam to Gulmarg (137.6 km, 3 hrs 40 mins)",
     p3:"Post breakfast, check out from the hotel and we will drive you to the hypnotic Gulmarg Valley. The valley offers two major attractions, the thrilling Gondola Ride, the second-longest and highest cable ride in the world and the adventurous sport of skiing. Adventure lovers flock here in great numbers from all over the world to enjoy skiing. The pristine views of snow-capped mountains are a great delight here. At night, enjoy a stay in the hotel in Gulmarg.",
     Day4:"DAY 4 : Departure from Gulmarg to Srinagar airport/railway station",
     p4:"This marks the end of your Kashmir tour for 3 Nights 4 Days! After breakfast, our representative will escort you to the Srinagar airport/railway station for the journey back home with memorable and pleasurable memories."
    },

];
export default PageContent;